# Generated by Django 6.1.1 on 2026-09-22 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='progress',
            options={'ordering': ['-date'], 'verbose_name': 'Body Analysis', 'verbose_name_plural': 'Body Analysis Records'},
        ),
    ]
