# Generated by Django 6.1.1 on 2026-09-20 01:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_records', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InitialAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.CharField(choices=[('weight_loss', 'Weight Loss'), ('weight_gain', 'Weight Gain'), ('body_recomposition', 'Body Recomposition'), ('healthy_eating', 'Healthy Eating')], max_length=30)),
                ('eating_habits', models.TextField(blank=True)),
                ('sleep', models.TextField(blank=True)),
                ('activity_level', models.TextField(blank=True)),
                ('previous_diets', models.TextField(blank=True)),
                ('challenges', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assessment', to='patient_records.patient')),
            ],
        ),
    ]
