# Generated by Django 6.1.1 on 2026-09-22 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient_records', '0002_initialassessment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='initialassessment',
            options={'verbose_name': 'Client Intake', 'verbose_name_plural': 'Client Intakes'},
        ),
        migrations.AlterModelOptions(
            name='patient',
            options={'verbose_name': 'Client', 'verbose_name_plural': 'Clients'},
        ),
    ]
