# Generated by Django 6.1.1 on 2026-09-22 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('receptionist', 'Receptionist'), ('diet_doctor', 'Nutrition Specialist'), ('exercise_coach', 'Fitness Coach'), ('follow_up', 'Follow-up Doctor')], default='receptionist', max_length=30),
        ),
    ]
