# Generated by Django 6.1.1 on 2026-09-19 21:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patient_records', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('doing_well', 'Doing Well'), ('review', 'Review'), ('needs_attention', 'Needs Attention')], default='doing_well', max_length=20)),
                ('meals', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('replacement_request', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_ups', to='patient_records.patient')),
            ],
        ),
    ]
