# Generated by Django 6.1.1 on 2026-09-22 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('follow_ups', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='followup',
            options={'ordering': ['-date'], 'verbose_name': 'Daily Check-in', 'verbose_name_plural': 'Daily Check-ins'},
        ),
    ]
