# Generated by Django 6.1.1 on 2026-09-22 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet_plans', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dietplan',
            options={'ordering': ['-start_date'], 'verbose_name': 'Nutrition Plan', 'verbose_name_plural': 'Nutrition Plans'},
        ),
        migrations.AddField(
            model_name='dietplan',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='dietplan',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dietplan',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='diet_plans/pdfs/'),
        ),
        migrations.CreateModel(
            name='DietPlanImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='diet_plans/meals/')),
                ('grams', models.PositiveIntegerField(blank=True, null=True)),
                ('substitutes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('diet_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_images', to='diet_plans.dietplan')),
            ],
            options={
                'verbose_name': 'Meal Photo',
                'verbose_name_plural': 'Meal Photos',
                'ordering': ['created_at'],
            },
        ),
    ]
