# Generated by Django 6.1.1 on 2026-09-22 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_appointment_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['date', 'start_time'], 'verbose_name': 'Booking', 'verbose_name_plural': 'Bookings'},
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('awaiting_confirmation', 'Awaiting Confirmation'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('no_response', 'No Response')], default='awaiting_confirmation', max_length=25),
        ),
    ]
