# Generated by Django 6.1.1 on 2026-09-22 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscription',
            options={'ordering': ['-start_date'], 'verbose_name': 'Membership', 'verbose_name_plural': 'Memberships'},
        ),
    ]
