# Generated by Django 6.1.1 on 2026-09-22 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise_plans', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exerciseplan',
            options={'ordering': ['-start_date'], 'verbose_name': 'Workout Plan', 'verbose_name_plural': 'Workout Plans'},
        ),
        migrations.AddField(
            model_name='exerciseplan',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
